// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJrnn49ADXjR4Q7mlgdaqxTWAnJRoFjrc',
    appId: '1:451211617188:web:671247dc212a9130655731',
    messagingSenderId: '451211617188',
    projectId: 'aniiii-f5f63',
    authDomain: 'aniiii-f5f63.firebaseapp.com',
    storageBucket: 'aniiii-f5f63.appspot.com',
    measurementId: 'G-FBJE2XTVPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIyFidAot2AFhtUod2Za30aALlXlRHSHA',
    appId: '1:451211617188:android:77f84fe4eb682d4c655731',
    messagingSenderId: '451211617188',
    projectId: 'aniiii-f5f63',
    storageBucket: 'aniiii-f5f63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5YpPMZpEyTE7spvxZ8KjGPRGBsPVyClA',
    appId: '1:451211617188:ios:11afbb02ec3a72b8655731',
    messagingSenderId: '451211617188',
    projectId: 'aniiii-f5f63',
    storageBucket: 'aniiii-f5f63.appspot.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5YpPMZpEyTE7spvxZ8KjGPRGBsPVyClA',
    appId: '1:451211617188:ios:11afbb02ec3a72b8655731',
    messagingSenderId: '451211617188',
    projectId: 'aniiii-f5f63',
    storageBucket: 'aniiii-f5f63.appspot.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJrnn49ADXjR4Q7mlgdaqxTWAnJRoFjrc',
    appId: '1:451211617188:web:b977457d368c9d97655731',
    messagingSenderId: '451211617188',
    projectId: 'aniiii-f5f63',
    authDomain: 'aniiii-f5f63.firebaseapp.com',
    storageBucket: 'aniiii-f5f63.appspot.com',
    measurementId: 'G-VHCKYM3WYS',
  );
}
